server:
  port: ${port}

spring:
  application:
    name: netflixgram
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${dbip}:3306/jhjeon?autoReconnect=true
    username: ${dbid}
    password: ${dbpass}
  mvc:
    view:
      prefix: /
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
---
mybatis:
  type-aliases-package: com.github.parkhana.dao
  mapper-locations: mapper/*.xml

---
logging:
  config: classpath:logback.xml
  level:
    net:
      chndol:
        study:
          mybatissample:
            mapper: DEBUG
