server:
  port: ${port}

app:
  upload:
    jhjeon: /Users/freshbread/Library/Mobile Documents/com~apple~CloudDocs/Projects/github/parkha-na/netflixgram/upload
    hana: C:/Users/white/Documents/workspace-spring-tool-suite-4-4.14.0.RELEASE/netflixgram/src/main/webapp/net/files
    server: /home/jhjeon/netflixgram/files

spring:
  application:
    name: netflixgram
  main:
    allow-circular-references: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${dbip}:3306/jhjeon?autoReconnect=true
    username: ${dbid}
    password: ${dbpass}
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
---
mybatis:
  type-aliases-package: com.github.parkhana.dao
  mapper-locations: mapper/*.xml

---
logging:
  config: classpath:logback.xml
  level:
    net:
      chndol:
        study:
          mybatissample:
            mapper: INFO
          